### ISSUE TITLE
Adding accessions from spreadsheet upload no longer working

### ISSUE THREAD

**Issue by ch728** [solgenomics/sgn#3833]
Adding accessions freezes here. The button "Add Accessions" does nothing when clicked .

![Screenshot from 2021-11-19 14-39-06](https://user-images.githubusercontent.com/36375878/142682092-6fc37e3b-b1e9-435f-b7ed-7f416c1ba335.png)

 I tried uploading a couple hundred accessions and then tried again with only 11 accessions. Doesn't seem to work either way.

**Comment by lukasmueller** [comment]
Fixed in version 0.36. I will update the site

**Comment by ch728** [comment]
Okay, let me know when it is updated and will check that it is working.

**Comment by lukasmueller** [comment]
one moment... ok, I think it is back up on version 0.36.

**Comment by ch728** [comment]
hmm, still doesn't seem to work for me. I tried upgrading my local test instance to v36 and got this error:

![Screenshot from 2021-11-19 15-45-03](https://user-images.githubusercontent.com/36375878/142689650-45fa7c0a-e744-4c69-b47b-1837d9b32bc5.png)

Wondering if the patches aren't working for v36 and this leads to the problem not being fixed?

**Comment by lukasmueller** [comment]
The patch that isn't working doesn't affect the problem. You may have to shift-reload the page before trying to upload again.

**Comment by lukasmueller** [comment]
But this dbpatch needs to be fixed as well... I just saw that too.

**Comment by ch728** [comment]
I had to close the browser. When I opened fresh and tried it worked!

**Comment by lukasmueller** [comment]
Great to hear :-)
